version: "3"
services:
  robot:
    image: robotframework/rfdocker
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444" 
    depends_on:
      - robot
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
